### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by DerEnderKeks** [dvx/lofi#10]
It would be nice if you could resize the window, as a size of 150px² might be fine on 1080p (or even 1440p like in my case) but I'm not sure how it would look on a 2160p screen.

**Comment by dvx** [comment]
This is something that will be definitely in the next minor release! Also a great new issue for anyone that wants to help out.

**Comment by janjur** [comment]
To me, lofi's great advantage is lack of config and minilalistic interface. I'd rather see automatic resizing based on resolution/dpi, than ability to resize myself. 
KISS, guyz.

**Comment by tonyreta03** [comment]
I just found the app and I love the concept of the app, I do wish that I could resize it so I will start working on that along with the random toggle.

**Comment by TKoBuquicious** [comment]
Any news on this, maybe?

**Comment by dvx** [comment]
@TKoBuquicious -- I'm exploring having 3 choices for sizing (tiny, classic, and larger) where classic is `150x150`. It might make it in the 1.5 release I'm planning for end of week.

**Comment by TKoBuquicious** [comment]
I would prefer it to be a bit more modular so that we can drag and expand to our size preference, honestly, but the 3 choices are good as a start too. Thanks!

**Comment by dvx** [comment]
Added resizing in 1.5.0!
