### ISSUE TITLE
i cant pause of play

### ISSUE THREAD

**Issue by letsummaybe** [dvx/lofi#105]
i cant pause or plays ongs iv tried everything i looked at other threads like this but sombody always says you need premeum to skip but remember pause i cant pause pls help

**Comment by pitermarx** [comment]
same here

**Comment by stamoun** [comment]
Freemium accounts cannot use playback buttons, this is a limitation of the Spotify API as per Lofi's [FAQ](http://www.lofi.rocks/help)
