### ISSUE TITLE
Can Not Use Music Control Buttons (play, rewind, skip)

### ISSUE THREAD

**Issue by Aeronaut59** [dvx/lofi#106]
I downloaded Lofi and connected it with Spotify, but while playing a song, the play rewind and skip buttons do not work. I tried uninstalling and reinstalling the app, deleting and redownloading the launcher, and turning off then turning on its access to Spotify, essentially giving it a "fresh start". None of these worked, and the buttons still do not control the music like they are supposed to.

**Comment by filiptrplan** [comment]
Are you on Spotify Free or Premium?

**Comment by Aeronaut59** [comment]
I am on Spotify free.

**Comment by stamoun** [comment]
Freemium accounts cannot use playback buttons, this is a limitation of the Spotify API as per Lofi's [FAQ](http://www.lofi.rocks/help)
