### ISSUE TITLE
Log In Page Not Working

### ISSUE THREAD

**Issue by GeoWolf75** [dvx/lofi#115]
When I try to link my Spotify account with LoFi, it comes up with an error from Heroku saying, "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command heroku logs --tail".

**Comment by dvx** [comment]
Heroku occasionally hiccups, it should be fine today! This ought to get fixed with the new release (no more `auth.lofi.rocks` endpoint management).
