### ISSUE TITLE
Suggestion: Like the Currently Playing Song

### ISSUE THREAD

**Issue by ejdub** [dvx/lofi#116]
I love Lo-Fi, but it would be SUPER helpful if there was a ❤️ button for the currently playing song. Thanks!

**Comment by dvx** [comment]
This was actually implemented by @stamoun in the current main branch. Unfortunately, I'm holding off on a full release until I re-write the entire window management (moving, resizing, etc.) as the new Electron version completely broke the old way of doing things. It's a hassle to re-write, and I've been working on other side projects so no real ETA atm, but you can always try building it from source yourself!
