### ISSUE TITLE
Window drifting even after mouse stopped moving

### ISSUE THREAD

**Issue by filiptrplan** [dvx/lofi#118]
This is an issue on the latest(as of writing) commit on the main branch: e33ac7c1e55e6c773c060946a867db4dea2b623d 

![lofi3](https://user-images.githubusercontent.com/8643457/115390434-86b8c600-a1de-11eb-87a8-0355a3a88526.gif)

As you can see, the window drifts even after my mouse stopped moving. Only after I let go of the mouse click it stops. This causes all kinds of problems like the window becoming unclickable.

**Comment by filiptrplan** [comment]
I will try to fix this by myself, I will let you know here if I am unable to.

**Comment by stamoun** [comment]
I'll look at the PR, I have yet to reproduce this bug myself, curious to know what causes it...
