### ISSUE TITLE
Add to Playlist functionality

### ISSUE THREAD

**Issue by Ghosty141** [dvx/lofi#124]
This would be the the feature I'd love to see the most. I often listen to playlists and think "oh this one is nice, I'll add that to mine". Doing this with the "fat" Spotify client is a bit annoying, that's why I think it'd be a good feature in lofi.

I've seen there is a pull-request for the "like" feature, are there pre-release builds already if you don't wanna release it for the general public? 

Thanks for the awesome player btw :)

**Comment by stamoun** [comment]
No pre-release yet, I'll be working on some sort of early access program for Lofi alongside a streamlined deployment mechanism (kind of like Discord's restart to update thing).

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
