### ISSUE TITLE
Can't see album art for local music files

### ISSUE THREAD

**Issue by matthewadamsdk** [dvx/lofi#125]
Firstly: I love this app, been looking for something like this for ages...

lofi has no problem showing the album art for streamed music on Spotify, but when I play local music files saved on the computer, lofi doesn't show the album art. The metadata for these local music files includes the album art & Spotify itself has no problem showing the album art, but lofi doesn't seem to be able to get hold of it.

Any thoughts on how to solve this?

**Comment by dvx** [comment]
This is a known issue and a `WONTFIX` for now, as it requires fiddling with the local filesystem to get album art (and has to be implemented for MacOS/Windows/Linux separately). With that said, it may eventually make it in.

**Comment by matthewadamsdk** [comment]
Thanks for taking the time to reply. :-)
