### ISSUE TITLE
dRequest - 32-bit Windows build

### ISSUE THREAD

**Issue by richb93** [dvx/lofi#130]
Running a super lightweight device with 2GB RAM - a PC on a stick device. The native Spotify client works but it's insanely slow and memory hungry.

Did some research and wanted to try this.

Any chance of a 32-bit build? Please and thank you.

**Comment by stamoun** [comment]
Lofi is not a standalone Spotify replacement, you still need to have Spotify running in the background somewhere. Are you asking for a standalone music player that streams from Spotify? That's not possible with Spotify's API sadly.
