### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Sssebek** [dvx/lofi#132]
Can't log in on my Spotify account.
After clicking 'Log in' in lofi, a http://auth.lofi.rocks/login opens in my browser with this error:
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by stamoun** [comment]
This should be addressed in `1.6.0` since we're moving with a different authentication mechanism. I think this issue can happen from time to time when the heroku app is down or sleeping. Have you tried again recently?

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
