### ISSUE TITLE
node-gyp doesn't target the right python install [Windows 10]

### ISSUE THREAD

**Issue by Devilmoon** [dvx/lofi#15]
When trying to build from source, node-gyp won't target the Python 2.7 installation by default if there's more than one Python installation on the machine. 

One can solve this by editing the package.json file and adding --python path/to/python27 to the build argument.

This should either be mentioned in the README, or another option would be to look into calling node-gyp through NPM so that the user can configure it to target python 2.7 automatically.

**Comment by dvx** [comment]
Looks like you fixed this in #16 -- thanks for the contribution!
