### ISSUE TITLE
Top portion of popup unclickable

### ISSUE THREAD

**Issue by Starstalker-awe** [dvx/lofi#161]
The top portion of the lofi app is unclickable, meaning I can't change settings and also have to go to the taskbar to close it. Not being able to change settings is the bigger of the two issues for me, if there is a config file somewhere in the folder, could someone name it for me?

Specs:
8gb RAM
Core i5 vPro
Integrated GPU
Windows 10 v 20H2

**Comment by victorioxd** [comment]
> and also have to go to the taskbar to close it. Not being able to change settings is the bigger of the two issues for me, if there is a config file somewhere in the folder, could someone name it for me?

I have the same problem, after deleting the `lofi` folder nothing changes, also tried to reinstall. I have not changed any configuration.

**Comment by stamoun** [comment]
So the top portion of the settings is offscreen?

Could you provide a screenshot please?

**Comment by victorioxd** [comment]
> So the top portion of the settings is offscreen?
> 
> Could you provide a screenshot please?

Sure here it is.

https://user-images.githubusercontent.com/74506415/160282225-9a237cea-595b-4497-a066-e9e5b9776ae8.mp4

**Comment by stamoun** [comment]
Ok, that is very weird, thanks for the video.
Is this on Linux by any chance? If so, it could be related to #87 

Could you enable the debug info (right-click on the Lofi icon in the system tray and open the settings) and check if there are any errors (other than `429 API throttling` ) in there?

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
