### ISSUE TITLE
Is it intentional that there is no pause button?

### ISSUE THREAD

**Issue by No1ofIntrst** [dvx/lofi#168]
I am on WIndows, using non-premium Spotify. 

I have noticed two relatively major issues with this player: Number one that I am unable to use the top of the player (as it fades out when I move my mouse from the middle), and number two that there is no pause button (the centre of the player shows only the "heart" button, rather than the pause button). 

Is this due to the same reason that you are unable to have skip buttons, or is it accidentally being disabled.

**Comment by joanbarros** [comment]
Hi @No1ofIntrst,

I don't get that behavior and I'm on Windows 10 using version 1.6. Which versions of Windows and Lofi are you experiencing the issue with?

Maybe a good test would be trying to reinstall the app to see if that fixes the issue.

**Comment by omarnoriega** [comment]
Howdy.
I have the same problem: doesn't show paly/pause button. Im usign loFi v1.6 and Windows 10.0.19043... I trtied reinstall the app but doesn't still works.

**Comment by stamoun** [comment]
You cannot control playback through the API on premium accounts as state [here](https://developer.spotify.com/documentation/web-playback-sdk/) 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/15142541/155825055-b13a186c-6858-40ef-a170-92469530e827.png">
