### ISSUE TITLE
Got Apple error about developer not verified - Sign binaries!!!

### ISSUE THREAD

**Issue by MatteoGauthier** [dvx/lofi#176]
<img width="369" alt="Capture d’écran 2022-01-27 à 14 41 12" src="https://user-images.githubusercontent.com/32040951/151370443-624c3c85-cca1-4225-971a-d68c05d769bc.png">

**Comment by stamoun** [comment]
Salut Matteo! :)

In order to be verified, we need to buy a certificate and sign the binaires. We need money for that, that being said, nothing stops you from looking at the source code and building your own version :)
I'd love, at some point, to have a properly signed installation for Mac.

**Comment by MatteoGauthier** [comment]
Thanks for your answer, nice to see that Apple continues to annoy the developers 🙃

btw bonne continuation 😄
