### ISSUE TITLE
Lofi constantly loses connection

### ISSUE THREAD

**Issue by egla89** [dvx/lofi#18]
Lofi loses seemingly randomly loses connection and I have to press the "Login" button again to reconnect. Unfortunately can't find a way to reproduce it reliably, it happens at different intervals.
macOS 10.14.3

**Comment by dvx** [comment]
Are you on an unreliable network? Occasionally, the Spotify API token expires (and we have to get a new one), but it should log you in automatically.

**Comment by egla89** [comment]
Yes can confirm that was the issue. Had a spotty connection that day, not enough for Spotify to skip or pause, but enough for lofi to disconnect a couple of times that day.
