### ISSUE TITLE
Controls not working unless Spotify is maximized

### ISSUE THREAD

**Issue by itzklyde** [dvx/lofi#183]
My controls hardly work unless the app is up and not minimized. It's not closed, it's minimized. The controls don't work very well though.  Kind of defeats the point if I have to have the app up and in my face. Any way to fix?

**Comment by stamoun** [comment]
Can you elaborate? What controls; media shortcut? Lofi's? Spotify's? What is `hardly` like not all the time (if so, may be related to API throttling)?
