### ISSUE TITLE
Can't install on linux

### ISSUE THREAD

**Issue by Alchiter** [dvx/lofi#188]
I'm running Ubuntu 20.04 LTS.
I'm trying to open the snap package, but the snap store doesn't recognize it. I can't build lofi myself because I'm having problems with python.

**Comment by stamoun** [comment]
Will be addressed along #174

**Comment by stamoun** [comment]
Try with `--dangerous`, it's because the apps are not signed (someday they will be, maybe?)...

https://snapcraft.io/docs/install-modes#:~:text=on%20confinement%20levels.-,Dangerous%20mode,unchanged%20during%20delivery%20and%20storage.

**Comment by tomasApo** [comment]
sorted! @stamoun 
![image](https://user-images.githubusercontent.com/75183079/179526167-88c03c0f-08a3-4e27-83aa-d332955da785.png)
