### ISSUE TITLE
Mac(High Sierra):  Lofi Opens but will not display anything

### ISSUE THREAD

**Issue by MustafaSquared** [dvx/lofi#19]
I have an early 2011 Macbook Pro 17 inch running High Sierra.  When I try to open Lofi, it will flash open and then anything that displays will suddenly disappear.  This all happens very quickly.  The computer will act like I have the app open, but nothing will display.

**Comment by dvx** [comment]
Hard for me to reproduce as I'm running Mojave. Can you find any Electron/Chromium logs by any chance?

**Comment by threkk** [comment]
I have exactly the same issue. Macbook 13" 2011 running High Sierra. Exactly the same.

**Comment by dvx** [comment]
Thanks for the report @cuddeford -- will investigate when I get some free time. (Un)fortunately, my daily driver is a Windows box so I haven't run into any issues.

**Comment by dvx** [comment]
Mind trying running Lofi again on 1.5.0? New release attempted to fix some of these issues.

**Comment by dvx** [comment]
Closing stale issue.
