### ISSUE TITLE
Black border after crash

### ISSUE THREAD

**Issue by Rucos64** [dvx/lofi#191]
App frozed and after restarting it came out with black borders. Nothing helped even deleting it. 
![image](https://user-images.githubusercontent.com/101583044/158214136-1b913410-8ba7-404f-8e19-6e391742f2b0.png)

**Comment by stamoun** [comment]
What OS?

You can try and clear the Settings file (on windows it's under `%appdata%\\lofi`

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
