### ISSUE TITLE
Change Account on lofi

### ISSUE THREAD

**Issue by Mendelyeev** [dvx/lofi#192]
Hi there. 

By mine mistake I logged in lofi with other account than I ussually use on spotify. Is there any way to change it?

**Comment by stamoun** [comment]
Yes, assuming you're under Windows, you can delete the file `%appdata%\lofi\Settings` (if your username is `foo`, it should be under `C:\Users\foo\AppData\Roaming\lofi`

**Comment by stamoun** [comment]
Will be fixed with #134
