### ISSUE TITLE
Can't Access Top Third of Lofi Window

### ISSUE THREAD

**Issue by He-ndrik78** [dvx/lofi#194]
help
plz

**Comment by stamoun** [comment]
lol, that's the most helpful message I've ever seen in an issue!

You can access the settings via the system tray (right-click on the lofi icon).

If you can't access the settings from there, please provide a bit more info...

**Comment by stamoun** [comment]
If I can translate OC's helpful comment, I think he's saying he can't access the top part of lofi, which is the same thing `Kiches` reported [here](https://discord.com/channels/730492151422779442/730492223724060746/971324211178127380). This is on Win10.

![image](https://user-images.githubusercontent.com/15142541/166705988-0e599ad7-6b1d-4cf9-9982-210eb180e4a7.png)

**Comment by He-ndrik78** [comment]
Hello, yes I am struggling with this issue and can't access the top quarter
of the lofi window it doen not allow me to click on the settings icon ,I
will reply to this email with a screen recoding of the window at a later
time.

**Comment by He-ndrik78** [comment]
https://user-images.githubusercontent.com/87751297/168415598-fbe9e71a-8119-4e15-98e7-297534b03ec4.mp4

**Comment by stamoun** [comment]
You can access the settings by right-clicking on the system tray icon for now

**Comment by stamoun** [comment]
Please don't close a bug because there's a workaround.

**Comment by Amador100** [comment]
i am having the same problem in  version 1.6 and 1.6.1. is there a fix yet?

**Comment by He-ndrik78** [comment]
Hello, not that I know of but you can right-click the icon in the system
tray to access the settings.
regards, Hendrik

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
