### ISSUE TITLE
Lofi not working at all

### ISSUE THREAD

**Issue by ray5647** [dvx/lofi#199]
the player doesn't show up at all, the program is open but i can't see the pop up. it's not hidden, it's simply not showing up so yeah idk how to fix it. tried reinstalling lofi and restarting my pc, neither worked.

**Comment by ray5647** [comment]
Windows 11, one monitor, and Lofi v1.6.0

**Comment by stamoun** [comment]
Thanks, no reason it shouldn't display. Would you mind sharing your settings file (should be under `%APPDATA%\lofi\Settings`); mainly the window x/y position. I feel like Lofi is rendering off screen, I've had a few users complaining about this in win11, but have yet to reproduce it myself.

**Comment by ray5647** [comment]
here is my settings file:

{"version":"1.6.0","debug":false,"hardware_acceleration":true,"lofi":{"visualization":0,"window":{"always_on_top":true,"show_in_taskbar":true,"x":2278,"y":4,"hide":false,"metadata":false,"scale":1,"side":217.9999996721744,"show_progress":false,"bar_thickness":1},"audio":{"volume_increment":10,"display_volume_change":false}}}

**Comment by stamoun** [comment]
Could you try and change `x` to like `200` you'd end up with something like (N.B. I also changed the `side` and `y` values)

```
{
  "version": "1.6.0",
  "debug": false,
  "hardware_acceleration": true,
  "lofi": {
    "visualization": 0,
    "window": {
      "always_on_top": true,
      "show_in_taskbar": true,
      "x": 200,
      "y": 200,
      "hide": false,
      "metadata": false,
      "scale": 1,
      "side": 150,
      "show_progress": false,
      "bar_thickness": 1
    },
    "audio": { "volume_increment": 10, "display_volume_change": false }
  }
}

```

**Comment by ray5647** [comment]
This worked for me! I have no idea how it occured as I didn't make any changes previously. Regardless, thank you for your help!

**Comment by stamoun** [comment]
No problem, now be aware that spotify has been throttling the heck out of our requests so controls may become unresponsive from time to time. When that happens you'll see the following on the app:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/15142541/163179422-aba6de82-e4da-4ad8-81f6-9b68c23cc791.png">

I have a possible solution (#190), but I need to finish the migration to electron 17 first and time is hard to get by :(
