### ISSUE TITLE
Visualizations not working?

### ISSUE THREAD

**Issue by frayedknot** [dvx/lofi#2]
Hi, I'm on OSX 10.14.2 (Mojave). It doesn't appear that the visualizations do anything in either the separate window or in the main window. They just seem to be static and do not change with the music.

If there's any other detail I can provide, please let me know.

**Comment by dvx** [comment]
To set up visualizations on a Mac, see the FAQ here: http://www.lofi.rocks/help

**Comment by frayedknot** [comment]
Whoops! Sorry, I missed that documentation. Thanks!
