### ISSUE TITLE
Black border around player on linux

### ISSUE THREAD

**Issue by Anti-Apple4life** [dvx/lofi#210]
Screenshot
![Screenshot_20220721_142823](https://user-images.githubusercontent.com/59315931/180287122-9ba8bbb3-36bd-4a45-b217-648ddd53e97a.png)

System Info
![image](https://user-images.githubusercontent.com/59315931/180287619-88676807-34fd-43cf-9630-29543ef3693c.png)

**Comment by Anti-Apple4life** [comment]
I am using the appimage

**Comment by stamoun** [comment]
Not too familiar with arch linux but is there a way to allow apps to use transparency? Basically the background for Lofi is black with an alpha value of 0...

**Comment by Anti-Apple4life** [comment]
I think it is something with KDE

**Comment by stamoun** [comment]
This is fixed in `2.0.0`
