### ISSUE TITLE
It would be nice if lofi could check the screen coordinates it uses on start up.

### ISSUE THREAD

**Issue by bhelyer** [dvx/lofi#212]
Lofi saves its window position in its settings file. This is usually the desired behaviour, but for those of us who have frequently changing screen topologies (at desk with two monitors, unplug for meeting, work at home with one monitor, for example) it's very easy to end up with a settings file where the coordinates place the entirety of the lofi window off screen.

Fixing this either requires manually updating the settings file's coordinates, or (on Windows) enabling the task bar button and using the keyboard to shephard it back. Neither of which is a giant deal, but ideally lofi should check to see if that it isn't entirely off screen before using the previous window coordinates.

**Comment by stamoun** [comment]
It should be fairly easy to check if the position is within the display(s) boundaries. If not, reset the position to center screen.
