### ISSUE TITLE
Cannot close full screen

### ISSUE THREAD

**Issue by MikeD579** [dvx/lofi#214]
when clicking the small button
![image](https://user-images.githubusercontent.com/28575292/183926679-818e69d3-decd-47a3-b794-1a332cc62b11.png)
it changes to change the GLSL animation. (Which doesn't make too much sense to me, but is beside the point.)
it also changes to the full screen icon
![image](https://user-images.githubusercontent.com/28575292/183927206-fb8f7f27-386d-4af1-aa86-f4f16587ef3c.png)
and when I click it it opens full screen. I cannot close the full screen. I have to close the app to get out of the full screen.
There should be an easy way to escape full screen. (This is especially annoying if all I want to do is switch back and forth from the GLSL animation to album art. I do not want to have to go into full screen and then back to the album art. Again beside the point.)

Pressing ESC should take you out of full screen. If this is already implemented, it did not work for me.

**Comment by stamoun** [comment]
Will be addressed in #242
