### ISSUE TITLE
Can log in to spotify, but when lofi asks me to log in, it tells me password or username is invalid.

### ISSUE THREAD

**Issue by geosolgeosol** [dvx/lofi#216]
I've verified my password, tried logging in  by email and username in the window lofi launches, but no matter what, it tells me username or password is incorrect.    I even went through the exercise of changing my password at Spotify, but still the same result.  
Windows 11 Pro,  Latest Spotify download.
Not sure if this is all the info that would help you.

**Comment by stamoun** [comment]
The username/password form is not from lofi, it's 100% driven by spotify. Not a Lofi issue
