### ISSUE TITLE
not detecting spotify

### ISSUE THREAD

**Issue by phillabust** [dvx/lofi#218]
![image](https://user-images.githubusercontent.com/114134982/191674177-e2ea312a-a9fb-4d66-a40e-1bab3cdec7e4.png)

just getting a flashing spotify logo. not sure what happened, it was working fine

**Comment by phillabust** [comment]
I tried re-installing lofi and spotify. even deleted all the roaming app data from lofi and re-logged into my spotify account, but it just won't work anymore. I did see a couple 429 errors at one point, but I can't find them anymore.

**Comment by stamoun** [comment]
Interesting, never seen this one before. Did your spotify account went from premium to free?

**Comment by phillabust** [comment]
Not that I'm aware of. Still premium

**Comment by stamoun** [comment]
The auth is failing for some reason, the above `Invalid state` is part of the auth flow.
The way auth works is that we let spotify handle the login/password part, then we get a state value (just 32 random bytes) that we compare against what we originally sent to spotify.

For some reason, in your case, the state doesn't match the original one.

When you authentify, what's the url you get where it says `Lofi authorization error: invalid state, you may close this window and retry.`

It should look something like (leave the code part out)

`http://localhost:41419/?code=...&state=PGFds88u5MnrtTU5_XckAM_DyN-hrXMmSFxNU3R9H6k`

**Comment by phillabust** [comment]
it randomly started working again. if it breaks again I'll look into it

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
