### ISSUE TITLE
Lofi will open in the hidden icons menu but no window appears

### ISSUE THREAD

**Issue by NowitsLeah** [dvx/lofi#219]
Mini player worked a few months back but have been lying dorment on my computer for a while, trying to open it again now with Spotify already playing it does not appear to be working the way I remember it doing. I can find it running in my task manager and opening the hidden icons menu on my taskbar reveals it hiding in the background, but I can't seem to get it to actually show up on my screen. Resetting the settings of the player or reinstalling it entirely has not made any changes.

**Comment by ElizaG00d** [comment]
> Did you delete the contents of `%appdata%\lofi` try that (if you're on Windows). On Mac it would be in `~/Library/Application\ Support/Lofi`

I had a similar issue, and it seems to work fine now after deleting the appdata, occasionally it gives me API calls errors though. Last time, it gave me the issue after I'd closed both it and Spotify. Hopefully it holds this time.

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
