### ISSUE TITLE
Visualizations not working for me on Win10

### ISSUE THREAD

**Issue by torrobinson** [dvx/lofi#22]
I absolutely love this widget, it harkens back to a time around 2005-2010 when little pixel-perfect minimal music and information widgets were all the shit for Mac OS and some got ported over to Windows. I love having this thing float above my windows while I work!

The issue: on Win10 Home, the visualizations appear to just be floating in their default state with no impact made by the Spotify music - is there anything I can do to troubleshoot why the widget doesn't appear to be getting an audio stream? The controls work perfectly otherwise.

Thanks!

**Comment by dvx** [comment]
I can't reproduce this. My only suggesteion is to make sure you run the player as Administrator.
