### ISSUE TITLE
I can't drag to the corner of the screen

### ISSUE THREAD

**Issue by oDevBR** [dvx/lofi#224]
I can move it to the back of the screen :(

![image](https://user-images.githubusercontent.com/33878228/202868766-34c79a27-0a8b-4f82-9864-7dd272a5d3fd.png)

It contains a margin of `322.047px`. I try made some changes here, but I had no success.

I'm using Ubuntu 22.04.1 LTS, 64-bit, Wayland

**Comment by stamoun** [comment]
Delete the settings.json file under the Lofi directory, it should be somewhere hidden in your home directory (sorry not on Linux right now)

**Comment by oDevBR** [comment]
> Delete the settings.json file under the Lofi directory, it should be somewhere hidden in your home directory (sorry not on Linux right now)

U mean, one of these files? Cuz I delete both and it just request to log in to Spotify again
![image](https://user-images.githubusercontent.com/33878228/203598221-3c61e6e5-f5a9-42de-b395-c384029696ba.png)

**Comment by stamoun** [comment]
ok, you can manually change the x/y values in there and get lofi to move further from the edge, it may help...

**Comment by stamoun** [comment]
This needs to be retested with 2.0.0, I've removed the weird app boundaries; the app now only takes the space that it needs.

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
