### ISSUE TITLE
No control arrows or pause button. Only Heart icon.

### ISSUE THREAD

**Issue by PsychePone** [dvx/lofi#226]
With win 11 I found a strange issue (I think) there are no controls at all. Even pause button. Funny thing is that the fav heart icon is there, and it's in the middle.
<img width="212" alt="2022-12-05 14_16_21-lofi" src="https://user-images.githubusercontent.com/73496181/205646485-e6d67d7b-e716-4135-b4f6-ff4f681e1d6f.png">

**Comment by stamoun** [comment]
Are you using a free Spotify account? If so, for some reason, Spotify disallows the use of playback buttons for free accounts (but you can still like songs...).

I'll close this if you are using a free account, it's in our [FAQ](https://www.lofi.rocks/help)

**Comment by PsychePone** [comment]
Bruh, that was quick response :D Yes, I'm using the free account. I thought the buttons will show up anyway... Volume control also doesn't work, but I suppose It's for the same reason?

**Comment by stamoun** [comment]
Yeah, anything that affects playback is disabled :(
