### ISSUE TITLE
15 seconds back/foward buttons

### ISSUE THREAD

**Issue by MrFixit12** [dvx/lofi#229]
I like to skip back a lot because i'm a terrible listener, Idk if theres a way to make this happen or not, but it would be cool

**Comment by MrFixit12** [comment]
this would fall under the enhancement category I think

**Comment by stamoun** [comment]
I know the original author wanted to keep the UI as minimalistic as possible and I tend to agree with that...

What if, instead, we skip back 10-15-whatever (configurable) seconds if the user clicks the back/fwd button while holding the control/option key 🤔

**Comment by MrFixit12** [comment]
sounds good to me, but isn't the control/option key sometimes a secondary action for the function keys?
