### ISSUE TITLE
Add option to lock/dock lofi to top menu bar

### ISSUE THREAD

**Issue by michal-sujkowski** [dvx/lofi#23]
It would be nice to have lofi docked/added to top menu bar. So it will be faster to find it.

**Comment by dvx** [comment]
I assume this would be a MacOS feature exclusively?

**Comment by michal-sujkowski** [comment]
> I assume this would be a MacOS feature exclusively?

If it make it more simple. Yes

Sorry for late reply.

**Comment by eralpsahin** [comment]
MacOS dock needs a 16x16 icon. If you can provide one, I would love to implement this.

**Comment by michal-sujkowski** [comment]
> MacOS menu bar needs a 16x16 icon. If you can provide one, I would love to implement this.

Like this one?

![icon_16x16](https://user-images.githubusercontent.com/12398253/66143632-cffaf200-e607-11e9-9f9e-f3712ec85a0b.png)

**Comment by dvx** [comment]
See also: http://www.lofi.rocks/favicon.ico

**Comment by michal-sujkowski** [comment]
What's up with this feature?

**Comment by dvx** [comment]
Added this feature in 1.5.0!
