### ISSUE TITLE
can't click on config or close in top of lofi

### ISSUE THREAD

**Issue by joseehilton147** [dvx/lofi#230]
If put mouse on top the hover doesnt work.

Mouse on middle
![1](https://user-images.githubusercontent.com/53986027/209964918-3dfcadbb-a065-4452-bc32-9823ddf890c4.png)

Mouse on top
![image](https://user-images.githubusercontent.com/53986027/209964922-11d2bb16-57b1-46b6-909b-a942ab4819f4.png)

I Have windows 11 22H2 22621.963 and using latest lofi version

**Comment by stamoun** [comment]
Duplicate of #204

**Comment by stamoun** [comment]
Most likely fixed in 2.0.1
