### ISSUE TITLE
The widget takes up tonnes of space of just black

### ISSUE THREAD

**Issue by Chompman32** [dvx/lofi#24]
https://imgur.com/a/4uezJE8   
The square around the album art in the centre of all black moves with the widget

**Comment by dvx** [comment]
This seems to be a transparency/3d acceleration issue. What video card do you have? Are you running in a VM?

**Comment by Chompman32** [comment]
GTX 960, no VM. Quick reply btw haha

**Comment by dvx** [comment]
Will investigate this, thanks for the report!

**Comment by FatherErickson** [comment]
I am experiencing this exact issue
https://imgur.com/a/1NMkTBQ

**Comment by dvx** [comment]
Attempting to fix this in 1.5 via a "Disable hardware acceleration" setting.

**Comment by dvx** [comment]
Should be fixed in 1.5.0!
