### ISSUE TITLE
Lofi doens't stay on top in windows 11.

### ISSUE THREAD

**Issue by Tycho-style** [dvx/lofi#243]
When I have Lofi player open everythings works fine except the On top function isn't working.

**Comment by koipolloi** [comment]
+1 on this bug.
When 'stay on top' is active, it actually progressively gets stuck in the z depth of other windows.

**Comment by LynnSnow13** [comment]
+1, except I'm on Windows 10 and I couldn't find an issue listed for 10. Was functioning fine yesterday when I installed it, after booting today, the widget is falling back but the song title and artist stay on top
![image](https://github.com/dvx/lofi/assets/110796108/790ac303-969a-415e-996e-533461c95504)

**Comment by stamoun** [comment]
You mean you have `always on top` disabled (false) but the track info stays always on top?

That'd be a regression I'll need to fix 😞

**Comment by stamoun** [comment]
No that's fine, just a brain fart in the code, should be easy to fix, I just have to get around to it.

I'll include this fix in the next release.

**Comment by lavendelchen** [comment]
this is still happening for me
