### ISSUE TITLE
Always show song is liked or not

### ISSUE THREAD

**Issue by martin-braun** [dvx/lofi#248]
I would love to see a little heart icon without hovering, because I don't like to miss a track that I like and forget to save in one of my playlists. I don't like hovering for every track just to find out the track is already liked by me or not.

Thanks!

**Comment by stamoun** [comment]
How bout a little heart next to the song title when a song is liked? Would that be enough?

Something like 👇 

<img width="391" alt="image" src="https://github.com/dvx/lofi/assets/15142541/82350c4a-81fe-43e1-8cda-76c09be19066">

**Comment by stamoun** [comment]
Granted, you'd have to leave the track info always on if you don't want to hover

**Comment by stamoun** [comment]
Done, will be available in the next release

MacOS:

<img width="270" alt="image" src="https://github.com/dvx/lofi/assets/15142541/40d1d48a-0730-42ee-88ab-492b1f788b9e">



Windows:

![image](https://github.com/dvx/lofi/assets/15142541/5bbb70f1-8144-4f98-bdcf-cada0da3eef0)

**Comment by martin-braun** [comment]
@stamoun That's pretty dope, thanks for that. :)
