### ISSUE TITLE
Log in to a Different account?

### ISSUE THREAD

**Issue by FreshieGeek** [dvx/lofi#25]
I use two accounts for two different types of listening, one for out and about, and one for home, both of which need to be kept separate. Can I log out of one account and into another?

**Comment by dvx** [comment]
Apologies for the late reply, but yes! You need to delete the Lofi configuration folder. Typically data is stored in the user’s “app data” folder. Where this directory is varies by operating system.

Mac OS: `~/Library/Application Support/Lofi`

Windows: `C:\Users<you>\AppData\Local\Lofi`

Linux (unsupported): `~/.config/Lofi`
