### ISSUE TITLE
Loggint out

### ISSUE THREAD

**Issue by BabyTaiyo** [dvx/lofi#250]
Hi! I was wondering if there was anyway to link the lofi spotify player to another spotify account. I recently made a new spotify account and wish to have the mini player reflect what music is playing on that account. Is there a way to relink the account? By the way I'm on mac.

**Comment by stamoun** [comment]
You can delete the confit file to réinitialiser the login. It’s under %appdata%\lofi\settings on windows

**Comment by BabyTaiyo** [comment]
Windows as in windows OS right? What about on MacOS?

**Comment by stamoun** [comment]
That would be in your home directory, Library, Application Support, Lofi (sorry on phone typing from memory 😅)

**Comment by BabyTaiyo** [comment]
Sorry the confit file?

**Comment by stamoun** [comment]
Config (silly autocorrect)

**Comment by BabyTaiyo** [comment]
There doesn't seem to be a config file.

<img width="835" alt="Screenshot 2023-02-28 at 8 34 27 PM" src="https://user-images.githubusercontent.com/81047795/222022140-5862933f-0bb5-46c1-8543-9b1ddf076590.png">

**Comment by stamoun** [comment]
It’s the `Settings` file (sorry it’s renamed to config.json in the latest upcoming version)

**Comment by BabyTaiyo** [comment]
Thanks so much it worked!
