### ISSUE TITLE
AppImage does not start

### ISSUE THREAD

**Issue by ChrisLauinger77** [dvx/lofi#255]
Hello,

I wanted to use the AppImage on debian bookwork.
starting with doubleclick on the appimage (made it executeable) does not work.
when I start it in a console I get:

 `./lofi-1.6.1.AppImage 

(node:26104) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[26104:0316/172444.373259:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst
christian@debian:/mnt/qnapnas01/install/linux/AppImages$ ./lofi-1.6.1.AppImage --disable-gpu
(node:26200) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[26200:0316/172620.778463:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/Breakpoint ausgelöst
`
what can I do to make it work ?
https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb

**Comment by stamoun** [comment]
You can try and disable the gpu in the settings file (I don't remember off the top of my head where that is stored in Linux distros, it should be in a lofi folder and named `config.json` in the latest release. Set the `isUsingHardwareAcceleration` to false in that file, see how that helps.

**Comment by ChrisLauinger77** [comment]
~/.config/lofi/Settings
I changed to:
{"version":"1.6.1","debug":true,"hardware_acceleration":false,"lofi":{"visualization":0,"window":{"always_on_top":true,"show_in_taskbar":true,"x":560,"y":140,"hide":false,"metadata":false,"scale":1,"side":150,"show_progress":false,"bar_thickness":1},"audio":{"volume_increment":10,"display_volume_change":false}}}
but still the same error

**Comment by ChrisLauinger77** [comment]
Thx this version works 4 me - it did not exist when I filed the bug
