### ISSUE TITLE
Slightly grey-out / blur the mini-player when paused?

### ISSUE THREAD

**Issue by janjur** [dvx/lofi#26]
Use-case:
headphones with touch control lying on a desk. I know I have to leave the desk for a significant amount of time. I use touch control (not working everytime), get visual on-screen confirmation that the music stopped. Happy to leave :)

**Comment by dvx** [comment]
Pretty good idea, might implement this. Thanks for the feedback!

**Comment by dvx** [comment]
Resolved by #39, closing!

**Comment by janjur** [comment]
When do you plan to release?

**Comment by dvx** [comment]
@janjur -- sorry, been kinda busy with work, but I'll most likely do a release sometime this week!

**Comment by janjur** [comment]
@dvx Thank you for the release! Planning to add Mac version as well? :D

**Comment by dvx** [comment]
Yep! I'll also rebuild it for OSX when I get on my MBP (~a few hrs),
