### ISSUE TITLE
Change default bar color

### ISSUE THREAD

**Issue by stamoun** [dvx/lofi#260]
Use a value easier on the eyes than #00FF00

Something like the following maybe?

![image](https://user-images.githubusercontent.com/15142541/234048856-0a6f5281-721e-4dc4-a9fe-64edd90a8298.png)

**Comment by ZaffyPuck** [comment]
What file/directory might this change be executed in?

**Comment by stamoun** [comment]
Where's the fun in telling you exactly where it is? ;)

Kidding, this is in the [constants](https://github.com/dvx/lofi/blob/master/src/models/settings.ts#L52) file
