### ISSUE TITLE
Indicate current track is liked or not in the menu bar

### ISSUE THREAD

**Issue by martin-braun** [dvx/lofi#271]
Hi,

this is a follow up to #248 which I'm very excited about, thanks a lot. I come to the realization that I'm sometimes on a fullscreen space and thus can't see lofi. It would be such a pleasure to also have a different menu icon if the current track is liked. I think this would be very great as an optional setting. Especially when the icon can be monochrome, so it better matches the design language of the menu bar.

My suggestion would be a heart icon that is outlined if the track is not in the "Liked Songs" playlist, or a filled heart icon if it is. It should also handle light and dark mode properly.

Thanks a lot for your great app! :)

**Comment by martin-braun** [comment]
@stamoun I kinda ended up [patching this behavior](https://github.com/Peter-Schorn/SoftPlayer/pull/6) into https://github.com/Peter-Schorn/SoftPlayer. So personally, I'm good now. Still, that might be a cool idea for your app as well, the overlay of lofi has some charm.

Decide yourself if this should stay open.

**Comment by stamoun** [comment]
Great idea, it's non-intrusive too. I like it.

**Comment by martin-braun** [comment]
Feel free to get inspired and copy whatever you need :) Glad you like it.

**Comment by martin-braun** [comment]
Now a dup of #272
