### ISSUE TITLE
Add option to hide non-premium warning

### ISSUE THREAD

**Issue by yav12** [dvx/lofi#286]
An option to remove this text would be nice: 
![prem](https://github.com/dvx/lofi/assets/80121423/3618c162-0d12-4fed-9ee8-cb3817f2b223)

**Comment by notNSANE** [comment]
I don't understand why the notice even appears there. Could be displayed inside the settings... It's just stupid.

**Comment by stamoun** [comment]
When it wasn't obvious that playback control were disabled, people were entering issues and whining on Discord that they didn't have any controls visible. Figured we'd make it obvious for that kind of users. Nothing 'stupid' there.

**Comment by notNSANE** [comment]
It's a terrible UX mistake. People perhaps need to show artist and song name and they're permanently reminded they're poor, too. A simple notice that can't be closed for 1 or 1:30 minutes would do the job just fine. Even accepting 100 popups would be better than a permanent notice.

**Comment by stamoun** [comment]
There will be, at some point, an option to hide it, hence this issue.

**Comment by stamoun** [comment]
New option in the track info settings:
<img width="428" alt="image" src="https://github.com/dvx/lofi/assets/15142541/79ce490e-c648-443a-9e6a-4005bb550074">
