### ISSUE TITLE
Get the initial position of the window from previous run

### ISSUE THREAD

**Issue by onurtore** [dvx/lofi#29]
I think it would be better to add this functionality. It's very bad to re-position the window everytime. If you guys want that, I might work on this.

**Comment by FreshieGeek** [comment]
I'd actually like it to snap to corners as well.

**Comment by dvx** [comment]
Feel free to pick this up @onurtore -- not too hard to implement, but there are a few edge cases. For example, if someone has dual monitors, drags Lofi on the secondary monitor, but then disconnects that monitor, and closes and re-opens Lofi, it will now have off-screen coordinates.

**Comment by onurtore** [comment]
@dvx  yeah, the first thing I thought, but still thanks for the heads up.

**Comment by FreshieGeek** [comment]
I get that, and it's a good point.
What I was referring to, I guess, is that I use Display Fusion on my dual
monitor setup, and i have my windows set to sticky.
For whatever reason, it doesn't see lofi as a window, so it doesn't stick
to the edges of anything.

**Comment by tonyreta03** [comment]
I just found the app and I love the concept of the app, I do wish that I could do such task so I will start working on that.

**Comment by dvx** [comment]
Fixed in 1.5.0!
