### ISSUE TITLE
[Feature Request] Add key shortcuts

### ISSUE THREAD

**Issue by Raizanad** [dvx/lofi#298]
Hello,

As a feature request can this player bind itself to spotify desktop to receive a ctrl + right arrow key or left arrow key to play next track or previous track respectively when the app is minimized? To not conflict with anything else I'd request that fn + right arrow key is equivalent to ctrl + right arrow and fn + spacebar to spacebar alone for pausing. This wouldn't conflict with anything Spotify TOS declares since multimedia keyboards can command spotify (directly or via windows universal media). Alternatively it would also work if you forego linking to spotify player and make a new app that allows a non multimedia keyboard to fn + right, left, pause, m and so on to control windows audio settings. I downloaded your app for those 2 things and the like button (I assumed those were built in) but now I'm invested enough to make this request.

**Comment by stamoun** [comment]
That's not a Lofi feature, that's an OS feature (media keys).

**Comment by Raizanad** [comment]
Yes, you are right.
