### ISSUE TITLE
Feature request: icon in notification area, not in taskbar

### ISSUE THREAD

**Issue by gh-nobi** [dvx/lofi#3]
I would prefer to move the icon from the taskbar to the notification area, to avoid clutter. It would make it more discreet, less in the way.

**Comment by dvx** [comment]
Great idea! Would also like to create a settings window (and it could be accessed from the taskbar context menu).

**Comment by mikaelmello** [comment]
https://electronjs.org/docs/api/tray

Besides that, just add `skipTaskbar: true` in `new BrowserWindow`

**Comment by dvx** [comment]
Implemented this feature and it will be available next release (1.5, hopefully by end of week).

**Comment by dvx** [comment]
Added in 1.5.0!
