### ISSUE TITLE
Now if it only had a volume control

### ISSUE THREAD

**Issue by Oxize** [dvx/lofi#30]
This widget would be so complete with a volume control. Is that possible?

**Comment by FreshieGeek** [comment]
I use 7 taskbar tweaker, which lets you adjust the volume by scrolling the
mouse when it's over the taskbar. It works great.

**Comment by dvx** [comment]
Any idea where to fit a volume control on the widget? I'd like to keep it as simple as possible.

**Comment by janjur** [comment]
That's pretty accurate concern. Maybe implement scrolling over the widget?

**Comment by dvx** [comment]
That could work, going to look into it!

**Comment by dvx** [comment]
I implemented this in #32 -- works via scroll-wheel over the main window. It will be part of the next release (1.2.0). Thanks for the idea @janjur!

**Comment by janjur** [comment]
Lets not forget @Oxize, who raised the issue. Glad I could help a bit :)

**Comment by janjur** [comment]
Volume control not working on Mac OS with magic mouse.

**Comment by dvx** [comment]
I'll test on MacOS today!
