### ISSUE TITLE
AUTH_CLIENT_ID Is it production key ? 

### ISSUE THREAD

**Issue by gunter423** [dvx/lofi#310]
Hello @dvx,

I would like to know if the key set in `/src/main/auth.ts` named `AUTH_CLIENT_ID` is configured to Production Mode or Development Mode (App Status) on your Spotify developer dashboard?

Have a nice day !

**Comment by stamoun** [comment]
@dvx ? I don't have access to the Spotify Dashboard

**Comment by dvx** [comment]
Spotify does not make a distinction between "production" and "development." The distinction it _does make_ is between "development" and "[extended quota mode](https://developer.spotify.com/documentation/web-api/concepts/quota-modes)" which relaxes some of the rate limiting and allows distribution without the need of a user whitelist. We obviously use the latter, or people couldn't install the app.

**Comment by gunter423** [comment]
Okay, thank you for this information !
