### ISSUE TITLE
[feature request] Minimize to system tray 

### ISSUE THREAD

**Issue by Peet0103** [dvx/lofi#314]
The app occupies too much space on the taskbar in Windows 11. Moving it to the system tray would be a better option.

**Comment by stamoun** [comment]
<img width="339" alt="image" src="https://github.com/dvx/lofi/assets/15142541/c82f7aa7-7134-46e7-b1c6-db8cc0779cca">

Can't you untick the `Display in taskbar` checkbox?
Does that achieve what you are trying to do?

**Comment by Peet0103** [comment]
om my, I didn't see that feature. Thanks!

________________________________
Van: Nicolas St-Amour ***@***.***>
Verzonden: donderdag 29 februari 2024 15:48
Aan: dvx/lofi ***@***.***>
CC: Peter Lassche (student) ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dvx/lofi] [feature request] Minimize to system tray (Issue #314)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>
image.png (view on web)<https://github.com/dvx/lofi/assets/15142541/c82f7aa7-7134-46e7-b1c6-db8cc0779cca>

Can't you untick the Display in taskbar checkbox?
Does that achieve what you are trying to do?
