### ISSUE TITLE
Question regarding visualizations and FFT

### ISSUE THREAD

**Issue by gillett-hernandez** [dvx/lofi#36]
is the data from `volume` equivalent to the raw audio data from the audio capture device?
if it is, then it might be possible to run a FFT on it and create visualizations based on the frequencies present in the music, not simply on the volume.

**Comment by dvx** [comment]
Hi @gillett-hernandez --

Unfortunately `volume` is just a float that indicates the "level" -- there are ways of getting the actual stream (and running an FFT on it), but I'm not an audio engineer and my brief attempts failed. Getting that data on Mac and Windows is also very different and requires getting in the weeds.

If you'd like to tackle decoding an FFT from the system audio streams, I'd be much obliged :)
