### ISSUE TITLE
Visualizations not working on W10

### ISSUE THREAD

**Issue by DimosthenisK** [dvx/lofi#40]
Greetings!

The visualizations in every song are practically static, staying the same through the entire song. Is this intended? Do I have to set up anything else besides the player?

I am already running it as administrator.

**Comment by dvx** [comment]
Hi there! Visualizations should be working on W10 (they work fine on my machine, for instance). Do you happen to have multiple output devices (e.g. speakers + headphones)? I think there might be an edge case there I'm not considering.

**Comment by DimosthenisK** [comment]
I managed to understand what was happening. The visualizations were off
because my volume was disabled. Is there any way to make the visualization
work, while having no sound? I am listening through my phone.

**Comment by dvx** [comment]
You do need to have your volume on for visualizations to work, as they use some W10-specific APIs to get sound volume. I think that doing it any other way (e.g. by recording time series FFT data) would, unfortunately, break Spotify ToS.

**Comment by DimosthenisK** [comment]
It's okay. I set my volume to 1 and it's working fine now. Thank you for
your time!

Στις Δευ, 9 Σεπ 2019 στις 9:45 π.μ., ο/η David Titarenco <
notifications@github.com> έγραψε:

**Comment by DimosthenisK** [comment]
Also, while listening through my headphones I indeed have no
visualizations, I only have them when using my speakers.

Στις Δευ, 9 Σεπ 2019 στις 9:48 π.μ., ο/η Dimosthenis Kalaitzis <
ftv.voidblaze@gmail.com> έγραψε:

**Comment by dvx** [comment]
Sounds good! Closing the issue.
