### ISSUE TITLE
Freezes my PC when trying to run without Spotify open

### ISSUE THREAD

**Issue by Darthagnon** [dvx/lofi#42]
I have a Win10 v1709 PC with Spotify 1.0.80.474 installed (BlockTheSpot installed, too). It's a Dell Inspiron 7577 with an Intel Core i7-7700HQ and a Nvidia GTX-1060 MaxQ. Plenty of RAM, HDD, etc. I installed Lofi and it promptly froze my PC. I hard reset, then upon restart, with nothing running in the background, tried again. It froze again, requiring another hard reset. Only then did I read the readme, and realise it only works with Spotify open. 

Uninstalled, as it did not work, and froze my PC :'(

**Comment by dvx** [comment]
This is very strange, it should absolutely not be freezing your PC. When running without Spotify open, it should simply display a glowing Spotify logo indicating that the client needs to be running.

Do you have any issues with other Electron apps (Slack/Discord, etc.)? The only thing I can think of is the volume detector, as it's hooking into some system calls, but it's not doing anything fancy.

**Comment by Darthagnon** [comment]
I have noticed cutting-edge modern Chromium 7x+ browsers (e.g. Vivaldi, MS Edgium Dev) sometimes glitching out the drop shadows on windows previews. Maybe it's graphics card related or something.

**Comment by dvx** [comment]
Can't reproduce this. Please try the newest 1.5.0 release which uses updated vesions of Electron and Chromium.
