### ISSUE TITLE
Like/Favourite songs through Lofi

### ISSUE THREAD

**Issue by polltery** [dvx/lofi#43]
### User story
When I am shuffling through random tracks while working, I love how Lofi's minimal UI helps me from being distracted. However, when it comes to saving a track to my library I have no option but to open up the main application, which causes minor distraction. It would be nice to have a save button in there as well.

### GUI suggestion
- Add a save button center aligned below the three main buttons (prev, play/pause, next)
![Lofi-HeartConcept-UI](https://user-images.githubusercontent.com/7419419/66229043-8a2b5000-e713-11e9-9a65-7ebde1f93bed.png)

**Note**
This will also require Lofi to update [Authorization Scopes ](https://developer.spotify.com/documentation/general/guides/scopes/) to the following
```
user-library-read%20user-library-modify%20user-read-playback-state%20user-modify-playback-state%20user-read-currently-playing
```
Mainly these two..
- `user-library-read` : To check if the current song already exists in user's library.
- `user-library-modify` : To add/remove song from user's library.

**Comment by dvx** [comment]
Solid feature request. Will work on this as I get some free time. I currently have a "shuffle + options" feature branch which I've been working on, so this might make it in that update.

Need to look into the edge-case of needing new scopes while permissions are "in flight." Might just have to blow up the settings and force a re-auth via Spotify.

**Comment by barnard-optician** [comment]
Yes would be great, thanks. Brilliant little app, thanks.

**Comment by CyberFoxar** [comment]
Might I add that, if the like function is added, could the dislike function be added too ? 
The stop button that appears in "Made for you" playlists.

**Comment by stamoun** [comment]
The hide/dislike button is also a great idea, however it seems like it's only valid for generated playlists. I think this could be split into a separate issue @dvx

**Comment by dvx** [comment]
Halfway implemented this a few months ago, and an issue I ran into is getting rate limited (Lofi polls Spotify every second, and there needs to be *another* polling that happens to see if the current song is favorited). There might be a way around it, but just something to keep in mind.

**Comment by stamoun** [comment]
Got ya, we could implement the `retry-after` from the Spotify's doc (https://developer.spotify.com/documentation/web-api/ section rate limiting).

**Comment by moxcx** [comment]
This would be amazing!!
