### ISSUE TITLE
Dragging the window freezes the GUI

### ISSUE THREAD

**Issue by akostet** [dvx/lofi#5]
In Windows 10:
The app starts in the center of the screen. The GUI works as expected until the window is dragged to a new position. The GUI then freezes in the "mouse hover" state (play controls showing as well as the song info tooltip to the right of the main window). 
All the controls are working but the GUI is not updated at all.

**Comment by dvx** [comment]
Unfortunately, I can't reproduce this.

**Comment by dvx** [comment]
Closing stale issue.
