### ISSUE TITLE
Feature request: Setting to show song and artist without hover

### ISSUE THREAD

**Issue by cfeied** [dvx/lofi#52]
I mostly listen to new/unfamiliar music and may not be able to put my hand on a mouse.

I want to glance over and see the current title and artist.

**Comment by dvx** [comment]
I think this ask would break my design goals of a `1x1` display ratio with only displaying album art. If someone would like to implement some settings that show text without hover, this might make it in, but it feels like feature creep.

So for now, this is a `WONTFIX`.
