### ISSUE TITLE
MacOS Player Position resets when screen locked

### ISSUE THREAD

**Issue by dyleroo** [dvx/lofi#54]
I use two monitors with my MacOS. I have the player in a specific place on the second monitor and when I lock my screen and unlock it the player shoots to the main monitor and i have to drag it back into place each time.

**Comment by dvx** [comment]
Thanks for the report, I'll take a look at this -- have a current patch I'm working on which tries to fix some of these position bugs on restart.

**Comment by dvx** [comment]
Should be fixed in 1.5.0.
