### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by lionnesquaer** [dvx/lofi#55]
Hello @dvx ! If you still working on improvement of LoFi, i want to ask for these improvements please:

1 Option of manual set size of widget
2 Option to set widget not "always on top"
3 Option to hide widget then Spotify closed or stopped

Hope you still working on LoFi! Becouse this is only one working mini player for Spotify now!

**Comment by dvx** [comment]
Hey @lionnesquaer -- thanks for the kind words! I am indeed still working on Lofi, although it's been a bit slow over the past half-year (Lofi is "good enough" for now).

With that said, I think (1) might add a bit too much complexity (I was thinking of just having two sizes: 100x100 and 200x200 which one could switch between). (2) and (3) are great suggestions and not super-heavy lifts.

**Comment by lionnesquaer** [comment]
@dvx Good to hear! Spotify company dont want to make native mini player, so it is good that somebody make it. Will be wait your update with improvements.

**Comment by Erim32** [comment]
Thx for your work,
Any update about this ?

**Comment by dvx** [comment]
Apologies for the belated updates. Still on the roadmap. I use Lofi daily so it's "good enough" for me, but I need to finish up a few feature branches (including this one). Work has been a bit crazy, but I'll get to this asap.

**Comment by BlakeKillough** [comment]
Yo, you are a true hero! Spotify should have developed a mini player years and years ago. My only request would be to have a simple toggle to always show song name, instead of only showing song name when you hover your mouse over it. This would make it great for streamers as well.

**Comment by dvx** [comment]
Just implemented: 

- Option to hide widget then Spotify closed or stopped
- Always show song info

This will make it in the next release (1.5), hopefully by end of week. Considering also adding a way of changing the player size.

**Comment by lionnesquaer** [comment]
@dvx Thank you! Will be wait next update! Please, implement feature make your mini player not always-on-top if it possible. Just personal habit from WinAmp use mini player as not always-on-top window. Thank you again!

**Comment by BlakeKillough** [comment]
@dvx Thank you man!

**Comment by dvx** [comment]
Implemented everything in here in 1.5.0. Please re-download and install, and thanks for the great feedback!
