### ISSUE TITLE
Media controls do not work at all

### ISSUE THREAD

**Issue by burritosoftware** [dvx/lofi#59]
Title. I can pause, rewind, and forward fine using my hotkeys or through the web app.

**Comment by dvx** [comment]
That's strange, my media controls work fine. Further, Lofi doesn't interact with media controls at all (those are handled by your OS + the Spotify client).

**Comment by burritosoftware** [comment]
Sorry for the late reply but yeah, I know that media controls are handled through the Spotify API. To check, I do recieve the spotify that is playing on my phone but I can't pause rewind fast forward or change volume of it.

**Comment by dvx** [comment]
Closing resolved issue (see Discord).
