### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by capaj** [dvx/lofi#6]
would be nice to have a debian package available

**Comment by Derpford** [comment]
If this is an electron app, yeah, any kind of linux build would be really nice. OpenSUSE here, would love to have this!

**Comment by dvx** [comment]
The build process itself should be easy-ish, but [volume natives](https://github.com/dvx/lofi/blob/master/src/native/volume/volume.cc) need to also be implemented for Linux.

**Comment by nilesr** [comment]
I inserted a dummy volume native that simply returns `rand() % 10`. This did not result in something that seemed to work well. There are bigger problems with a linux version. Here's what it currently looks like on my machine:


![2019-02-25-185029_1919x1079_scrot](https://user-images.githubusercontent.com/1323220/53377099-a5053d00-3958-11e9-93b3-bef1a64b7224.png)

**Comment by dvx** [comment]
Thanks @nilesr ! I figured as much -- I use a few transparency tricks to dodge a really annoying Mojave issue (see https://github.com/electron/electron/issues/13164) so I'm not surprised it has weird side-effects on systems I haven't tested.

Looks like the process will be a bit more involved.

**Comment by dvx** [comment]
FYI, lack of transparency on Linux might be related to this open ticket: https://github.com/electron/electron/issues/15947

(Looks like it might be fixable with some flags? Or maybe a bump in the Electron version we're building against.)

**Comment by dvx** [comment]
Linux version (sans visualizations) added with 1.5.0!
