### ISSUE TITLE
Lofi crashes when switching to particular albums.

### ISSUE THREAD

**Issue by bhelyer** [dvx/lofi#62]
## Steps to reproduce:
  1. Start playing the first track of this album https://open.spotify.com/album/6Jqu2NBFCrT1lsR6YTWhZw?si=P17yk9frQBmQhaQ6-GIEkg
  2. Open Lofi
  3. Double click the first track again, once the album art displays.

## What do I expect to happen?
 - Lofi to stay right where it is.

## What actually happens?
 - The lofi window vanishes. It remains in the task manager, and in the task bar, and must be manually closed.

Not every album/song does this.

[A zip file containing a video reproduction.](https://github.com/dvx/lofi/files/4822582/2020-06-24.12-33-51.zip)

**Comment by dvx** [comment]
Thanks for the report @bhelyer -- I literally *just* fixed this bug, so your report is eerily serendipitous 👻 For whatever reason, the Spotify API sometimes returns an empty `currently_playing` object without any `currently_playing.item` so the player crashes, expecting the player to be playing.. something. The fix will make it in the next release! I have a hunch this also fixes #7 and am testing that next.

**Comment by dvx** [comment]
Should be fixed in the newest release!

**Comment by bhelyer** [comment]
Looks fixed over here too. Thanks!
