### ISSUE TITLE
[Suggestion] Volume increment setting

### ISSUE THREAD

**Issue by iCeCoCaCoLa64** [dvx/lofi#67]
One feature I really like about this mini player is that while you're hovering over it, you can use the mouse wheel to adjust the volume. However, scrolling raises/lowers the volume by 10 which I feel is a bit too much.
Suggestion: Add a setting that lets users customize how much the volume gets raised/lowered every time you scroll. Example: My volume is currently at 30, and my volume increment setting is 2, so if I scroll up while hovering over the mini player, my volume increases to 32.
I'm not a coder, so I don't know how difficult and/or time-consuming it would be to add this in, but hopefully this would be a simple addition, I would really like to see this added.

**Comment by dvx** [comment]
Thanks for the suggestion! Could be a good idea if anyone wants to tackle it (shouldn't be too hard). This is the relevant method: https://github.com/dvx/lofi/blob/4ca930ec958ae1dc7ed3ed1105c905ae66fda372/src/renderer/components/Lofi/Cover/index.tsx#L44

**Comment by stamoun** [comment]
For some reason I have no clue how to link the above commit/PR to this issue...

**Comment by dvx** [comment]
Fixed by #71 -- closing!
