### ISSUE TITLE
"Hide Lofi window if Spotify is not detected" doesn't work at all

### ISSUE THREAD

**Issue by iCeCoCaCoLa64** [dvx/lofi#68]
Switched to Spotify a few days ago and got Lofi with it. Lofi seems to work just fine for me aside from this one issue. The Lofi window will stay on screen at all times, even if Spotify is closed. I don't see any other posts about this issue, so I'm not sure if it's an actual bug with Lofi, or if something on my PC is causing the window detection to mess up, but either way I'd like some help fixing it.

Some misc info if it matters:
- OS is Windows 10 Pro 64bit
- I'm using a normal Spotify installation, not the Windows 10 store app
- I have all other settings enabled as well, except for debug mode

**Comment by dvx** [comment]
This is working as intended. Lofi uses a "keep alive" if a song was started and then paused to remember your position on the track. The "window hiding" feature is meant to be used if Spotify gets fully closed (not just minimized). Maybe I'll change the behavior in the future, but that's the rationale behind it.

**Comment by iCeCoCaCoLa64** [comment]
I _do_ fully close it. I have Spotify set to actually close itself, not just minimize to the tray. But even when Spotify is closed, nothing in my task manager suggesting it's still open in some way, Lofi stays open.

**Comment by dvx** [comment]
Basically if Lofi gets nothing in the `currently_playing` payload, it minimizes, as per this code:

https://github.com/dvx/lofi/blob/4ca930ec958ae1dc7ed3ed1105c905ae66fda372/src/renderer/components/Lofi/Cover/index.tsx#L115

There are a few ways Spotify can still return `currently_playing` in the `/player` payload while still being shut down on your PC (including, for example, being open on your phone). You can observe this payload yourself by looking at the `debug` output.
