### ISSUE TITLE
Window becomes invisible when playing local files

### ISSUE THREAD

**Issue by stevenbrz** [dvx/lofi#7]
(Running Windows 10)

When a local file gets played, the window disappears and lofi requires a restart to function again even after switching to a song belonging to Spotify. The icon remains on the taskbar and the process is still "responding" according to Windows.

**Comment by dvx** [comment]
Very interesting, was not even aware that Spotify can play local files. I wonder what the Spotify API sends back in those cases. Will investigate, thanks for the report!

**Comment by DeltaCore** [comment]
I can confirm this behavior.

You can enable local files in settings:
![screenshot_27](https://user-images.githubusercontent.com/5575913/53728023-f38f6b80-3e71-11e9-98d2-39a99650b7a3.png)

It probably has todo with the fact that local files don't have an album cover and maybe it fails to load that inexisting cover.

Are there any log files we can provide to make it easier for you to track down the issue?

- Marcel

**Comment by dougcotler** [comment]
I'm on Mac. This sometimes also breaks the app though most times it will fix itself when a non-local file starts playing again. Other third party things I've used have been able to get the local file info from the API so should be an easy fix I think.

**Comment by eralpsahin** [comment]
I looked into this and seems like this happens for podcasts, videos, and local files.

Podcasts and videos have no `currently_playing.item`. So accessing that for `duration_ms` in `getTrackProgress()` throws an exception.

Additionally, local files have item but they have no `currently_playing.item.album.images`. So accessing that in `getCoverArt()` throws an exception.

**Comment by vanstek** [comment]
Happens for local files for me too. The player disappears and I can't get it back unless I restart the program while playing a song belonging to Spotify. If I'm playing a local file and open lofi, it auto exits and I have to restart.

**Comment by dvx** [comment]
Fixed this and will be available in the next release (1.5, by end of week).

**Comment by dvx** [comment]
Fixed in 1.5.0!
