### ISSUE TITLE
Linux build just shows Spotify logo after logging in

### ISSUE THREAD

**Issue by trisk** [dvx/lofi#70]
Installed on Ubuntu 20.04 with:
`sudo snap install --dangerous lofi_1.5.0_amd64.snap`
It opened a browser window to log into Spotify, successfully logged in but the lofi window now just shows a strobing Spotifying logo.

**Comment by dvx** [comment]
This means that you need to make sure Spotify is running and playing a song. See the FAQ for more details.

**Comment by mpowell326** [comment]
I also installed on Ubuntu 20.04 with:
`sudo snap install --dangerous lofi_1.5.0_amd64.snap`

Only works for me with the debian spotify version but not the snap spotify. 
(See https://www.spotify.com/nz/download/linux/b/)
