### ISSUE TITLE
Use PKCE for Authorization

### ISSUE THREAD

**Issue by stamoun** [dvx/lofi#73]
The app seems to currently using Code Flow for authorization with a lofi server running on http://auth.lofi.rocks. Usually SPAs (or electron apps?) use PKCE to grant authorization.

Using PKCE would remove the need to have a backend server validating the auth. An added benefit would be the possibility to have an offline mode (although I'm not sure if you can access Spotify's downloaded tracks via some sort of local api, it seems supported by [Android and iOS](https://developer.spotify.com/community/news/2019/11/27/offline-mobile-sdk/))

See the [Authorization Code Flow with PKCE](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce) for more info.

p.s.: I don't know how to reach you other than through issues/comments and I don't want to burden you with issues. If you want to reach out directly to me, you can mail me at my username @gmail.com)

**Comment by dvx** [comment]
Good catch, wasn't aware Spotify had PKCE. This is a pretty heavy lift, but should probably be implemented at some point.

**Comment by stamoun** [comment]
I started looking into this for fun (never implemented PKCE so thought I'd take a stab at it), would you mind sending me the client id you use for lofi? Either via email or here, it shouldn't be a secret. thanks! It should be available https://developer.spotify.com/dashboard/applications

**Comment by dvx** [comment]
Sure thing @stamoun -- the client ID is `69eca11b9ccd4bd3a7e01e6f9ddb5205`

**Comment by dvx** [comment]
#81 fixes this. Closing.
