### ISSUE TITLE
Mission Control Window Size Bug on Mac

### ISSUE THREAD

**Issue by RoyShtayim** [dvx/lofi#75]
<img width="838" alt="Screen Shot 2020-08-11 at 18 53 15" src="https://user-images.githubusercontent.com/68990959/89919536-0f20a900-dc04-11ea-820b-baed2c69c951.png">

**Comment by dvx** [comment]
Yeah, this isn't a bug, it's actually a workaround. Until Electron fixes native frames, I need to extend the window bounds past the monitor bounds to have nice clean shadows. For now, it's a `WONTFIX`.

To see exactly why we need this, feel free to look at the black magic native libraries where I reference the Electron bugs.
