### ISSUE TITLE
Request for Windows 10 - Hide from Taskbar

### ISSUE THREAD

**Issue by solondesign** [dvx/lofi#80]
Could you consider including an option to prevent the icon from being displayed in the taskbar (unless it's pinned)?

Thanks so much!

Matt

<img width="625" alt="Screenshot 2020-08-23 230744" src="https://user-images.githubusercontent.com/45156720/91009497-8a377700-e595-11ea-833e-d490e49464c1.png">

**Comment by stamoun** [comment]
If you select the option to have Lofi 'always on top' of other windows, it will not display itself in the taskbar. That being said, this is not exactly what you are asking, I think an option could make sense, a 'minimize to tray' type thing

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
