### ISSUE TITLE
State mismatch when connecting Spotify the first time

### ISSUE THREAD

**Issue by Khormin** [dvx/lofi#89]
Windows 10 environment, using Chrome to connect to Spotify.

Steps to reproduce:

- Load lofi.beats client
- Log in button
- Log into Spotify via accounts.spotify.com/authorise response
- Get taken to http://auth.lofi.rocks/#error=state_mismatch

**Comment by stamoun** [comment]
What OS are you running? What version of Lofi?

**Comment by Khormin** [comment]
Windows 10, as stated.  64-bit build.

I'm going to have to guess 1.5.0 Lofi as that's what the installer says, but unfortunately neither site nor client is telling me.

**Comment by stamoun** [comment]
Would you mind showing the debug console (specially the network tab)? A state mismatch is when a code in the payload to finalize the authorization does not match its original value when the authorization started.

**Comment by dvx** [comment]
Closing stale issue. Re-open if problem persists.
