### ISSUE TITLE
Access token was bad...renewing

### ISSUE THREAD

**Issue by Proxo97** [dvx/lofi#90]
Windows 10, Latest Lofi Version:

When I press log in and get taken to the spotify authorization site, after I click "Agree" I get taken to
"http://localhost:41419/?access_token=TOKEN_STRING&refresh_token=TOKEN_STRING", the page stays blank and the debug console starts throwing errors:

![unknown (9)](https://user-images.githubusercontent.com/48361658/95615346-60b0ad00-0a68-11eb-8e65-ebc34990a20b.png)

**Comment by stamoun** [comment]
That means your authorization when through successfully. The `429` errors is the Spotify Backend throttling the requests (i.e. ignoring them and returning `429`). The `1.5.0` refreshed the access token whenever the API didn't return a 200 upon launch.

If you relaunch the app you still get the error?

Api throttling (`429`) have been occurring a lot lately. Also note that the upcoming release handles these errors differently.

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
