### ISSUE TITLE
Stuck "verifying access token..."

### ISSUE THREAD

**Issue by Speeko** [dvx/lofi#91]
Clicking log in opens my default browser (Brave) and I sign in to Spotify successfully.

Access token is returned as: http://localhost:41419/?access_token=[redacted]

Lofi window then hangs on 'verifying access token'

![image](https://user-images.githubusercontent.com/6498214/97383728-36d10480-1909-11eb-9d50-fb716dabaf6b.png)

![image](https://user-images.githubusercontent.com/6498214/97383751-405a6c80-1909-11eb-9065-0c8191b66628.png)

**Comment by dvx** [comment]
Possibly related to #90

**Comment by stamoun** [comment]
Most likely fixed in `1.6.0`

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
