### ISSUE TITLE
Window not on top

### ISSUE THREAD

**Issue by jamesjhuang** [dvx/lofi#97]
"Show Lofi window always on top" is checked off and Lofi has been restarted. Lofi window seems to be able to overlay on most apps, except for Microsoft Edge. Other apps are able to go on top of Microsoft Edge (this includes apps that Lofi is able to go on top of).

Lofi window also doesn't always go on top of apps it's previously been able to go on top of.

OS: Windows 10

**Comment by stamoun** [comment]
Fixed in [v1.6.0](https://github.com/dvx/lofi/releases/tag/v1.6.0)
