### ISSUE TITLE
[Linux] Black box around cover

### ISSUE THREAD

**Issue by matbonucci** [dvx/lofi#98]
I'm using Lubuntu 20.04
Black box shows up but when I enable Compton and restart Lofi a transparent box shows instead
![screen-2020-12-22 2111](https://user-images.githubusercontent.com/5504686/102939135-941aa980-44a5-11eb-96bd-3828c65a813f.png)
![screen](https://user-images.githubusercontent.com/5504686/102939140-97ae3080-44a5-11eb-8a10-ba919deb4a81.jpg)

**Comment by letsummaybe** [comment]
hey i cant even downlad it ur lukey

**Comment by matbonucci** [comment]
> hey i cant even downlad it ur lukey

https://github.com/dvx/lofi/releases/tag/1.5.0
For linux you can use the .snap or .AppImage

**Comment by matbonucci** [comment]
I fixed it by disabling "Enable client-side shadows on windows" on Compton settings

**Comment by sheeepdev** [comment]
I can't solve this, I don't even have that option enabled in picom/compton
